google-org/new-project-ny

web/frontend/src/components/Home.jsx
web/frontend/src/components/Person.jsx
web/src/main/java/org/google/newprojectny/api/PersonController.java
web/src/main/java/org/google/newprojectny/dao/FakePersonDataAccessService.java
web/src/main/java/org/google/newprojectny/dao/PersonDao.java
web/src/main/java/org/google/newprojectny/service/PersonService.java

- Returns new Person after creating one in DB
- Calls API routes from React FE and uses responses to populate the UI
- Outstanding issue: /home not working

Call API routes from frontend to populate people. Update backend route to return new Person after creating one.

---

README.md

just playing around with github for now & wanted to try out a PR

Updated project title

---

call-me-back-app/web/src/main/java/org/google/callmeback/DemoPersonApi.java
call-me-back-app/web/src/main/java/org/google/callmeback/api/PersonController.java
call-me-back-app/web/src/main/java/org/google/callmeback/dao/FakePersonDataAccessService.java
call-me-back-app/web/src/main/java/org/google/callmeback/dao/PersonRepository.java
call-me-back-app/web/src/main/java/org/google/callmeback/model/Person.java
call-me-back-app/web/src/main/resources/application.properties
hello-world-app/web/src/main/java/org/google/helloworld/DemoPersonApi.java
hello-world-app/web/src/main/resources/application.properties

Finally got a basic endpoint working to call mongo (locally) with insert/select outputs like this:
[{"id":"251ba8c5-336a-4c1a-841e-c081b464eda1", "name":"Alice","status":"WAITING","phoneNumber":"555-555-5555"},{"id":"1829a90b-5c2a-4d2b-bcf1-7be06b85875c","name":"Bob","status":"CALL_IN_PROGRESS","phoneNumber":"555-555-5556"}]
Also made some fixes that were referencing "hello world" instead of "call me back" in the imports.

basic localhost mongo api control for callmeback

---

README.md

Updated README with notes on minikube/gradlew start

---

README.md

Updating the README with the commands to stream logs from running containers.

Updating README to include log viewing instructions.

---

callmeback/frontend/src/components/CancelConfirmation.jsx
callmeback/frontend/src/components/ThankYou.jsx

Use <Link> elements to route back to home page instead of href's because it avoids the Redirect issue

Change routing back to homepage to work around necessary Redirect config change

---

callmeback/frontend/src/components/Feedback.jsx
callmeback/frontend/src/components/Reservation.jsx

Update reservation by calling API on feedback page

---

callmeback/frontend/src/components/Cancel.jsx
callmeback/frontend/src/components/Feedback.jsx

Call backend to cancel reservation

---

callmeback/frontend/src/components/WaitDetails.jsx

https://user-images.githubusercontent.com/29430896/80845409-1b45a500-8bd7-11ea-854e-03709721866a.png

Add checkbox for texting

---

callmeback/frontend/src/components/Home.jsx

Updated regex to prevent 7 digits and allow parens

---

README.md
callmeback/frontend/public/index.html
callmeback/src/main/java/org/google/callmeback/CallMeBackController.java

Add support for React routes by adding a new CallMeBackControlller and explicitly listing the React routes that require redirection.

Add support for React routes

---

.github/workflows/linting.yml

Upgrade format script to use JDK 11

---

callmeback/frontend/src/components/FAQAccordion.jsx
callmeback/frontend/src/components/Reservation.jsx

Fixes #99 
Updated FAQs with the sample question from the mock https://gallery.googleplex.com/projects/MCHbtQVoQ2HCZR4FoCy-jZSS/files/MCEJu8Y2hyDScePayAkDyastgC15FPSYUUY plus two I came up with.

Update FAQs to be about Business instead of Employment

---

callmeback/frontend/src/components/Feedback.jsx

Fixes #93 
Changes wording on feedback page

Change call back to call on feedback page

---

callmeback/frontend/src/components/FAQAccordion.jsx
callmeback/frontend/src/components/Home.jsx

Also remove an unused import
Fixes #94

Make all 3 fields on form required for submission

---

callmeback/src/main/java/org/google/callmeback/api/ReservationWindow.java

Fixes #89 
Make call back window 20-40 minutes instead of 10-30

Change wait window to 20-40 minutes

---

callmeback/README.md

Update README to reference callmeback application

---

.github/PULL_REQUEST_TEMPLATE.md

Add reminder to flesh out features in design before submission

---

helloworldredux/README.md

Based off of @tariqajyusuf 's branch; just updates the README. Should be submitted after Tariq's branch is pushed so that only the Mac instruction changes show up here

Instructions for infra refactor for Mac

---

callmeback/build.gradle
callmeback/src/test/java/org/google/callmeback/api/ReservationRepositoryTest.java

Added tests for ReservationRepository

---

callmeback/src/main/java/org/google/callmeback/api/Reservation.java
callmeback/src/test/java/org/google/callmeback/api/ReservationRepositoryTest.java

Updated ReservationRepository tests to test for equality

---

simulation/producer/README.md
simulation/producer/lib/simulation.js
simulation/producer/package-lock.json
simulation/producer/package.json

Fixes #117 
Do not yet take into account the speed up factor. Update README accordingly.

Send reservationCreatedDate from Producer script

---

callmeback/README.md

Fix newline that broke script

---

callmeback/backend/src/main/java/org/google/callmeback/api/CustomizedReservationRepository.java
callmeback/backend/src/test/java/org/google/callmeback/api/ReservationRepositoryTest.java

Cleanup warnings

---

callmeback/backend/src/main/java/org/google/callmeback/api/CustomizedReservationRepository.java
callmeback/backend/src/main/java/org/google/callmeback/api/QueueingRepository.java
callmeback/backend/src/main/java/org/google/callmeback/api/Reservation.java
callmeback/backend/src/test/java/org/google/callmeback/api/ReservationRepositoryTest.java
callmeback/frontend/src/components/Home.jsx
simulation/producer/lib/simulation.js

Rename Reservation.reservationCreatedDate to requestDate

---

simulation/consumer/lib/simulation.js
simulation/consumer/main.js

Construct reservation URL instead of using the one provided by API

---

callmeback/backend/src/main/resources/application.yml
callmeback/kubernetes/ingress.yaml
simulation/consumer/lib/simulation.js
simulation/consumer/main.js

Fix URL for API path

---

callmeback/frontend/src/components/Cancel.test.js

Test Cancel React Component

---

callmeback/frontend/src/components/WaitDetails.jsx

Fixes #175 
> It's a good idea to open an issue first for discussion.

remove issue of having a <div> within a <p>
